# Generated by Django 3.2.6 on 2021-09-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_promocion', models.CharField(max_length=20)),
                ('tipo_promocion', models.CharField(choices=[('D', 'DESCUENTO'), ('P', 'PORCENTAJE')], max_length=2)),
                ('valor_promocion', models.IntegerField()),
                ('subtotal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('tamano', models.CharField(choices=[('ST', 'STANDARD'), ('CH', 'CHICO'), ('ME', 'MEDIANO'), ('GR', 'GRANDE')], max_length=20)),
                ('precio', models.PositiveBigIntegerField()),
                ('categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Inventario.categoriasproductos')),
            ],
        ),
    ]
