# Generated by Django 3.2.6 on 2021-09-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_remove_promocion_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='valor_promocion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
