# Generated by Django 3.2.6 on 2021-11-19 13:50

import MODULOS.Inventario.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_alter_promocion_valor_promocion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='valor_promocion',
            new_name='valor_promocion_fin_de_semana',
        ),
        migrations.AddField(
            model_name='promocion',
            name='valor_promocion_semana',
            field=models.IntegerField(default=100, validators=[MODULOS.Inventario.validators.ValorPromocionValidador]),
            preserve_default=False,
        ),
    ]
