# Generated by Django 3.2.6 on 2021-09-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Empleados', '0001_initial'),
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(choices=[('FRIA', 'COMIDA FRIA'), ('FM', 'FALTÓ MERCADERIA'), ('ME', 'MALA PRESENTACIÓN'), ('MD', 'MUCHA DEMORA'), ('MA', 'MAL ARMADO DEL PEDIDO')], max_length=10)),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.pedido')),
            ],
        ),
    ]
