# Generated by Django 3.2.6 on 2021-09-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
