# Generated by Django 3.2.6 on 2021-09-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0002_auto_20210924_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartpromociones',
            old_name='promocion',
            new_name='id_promocion',
        ),
    ]
