# Generated by Django 3.2.6 on 2021-09-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_alter_promocion_valor_promocion'),
        ('Carrito', '0003_rename_promocion_cartpromociones_id_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpromociones',
            name='id_promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.promocion'),
        ),
    ]
