# Generated by Django 3.2.6 on 2021-11-22 18:58

import MODULOS.Carrito.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0005_auto_20210926_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[MODULOS.Carrito.validators.CantidadMayorCeroValidador]),
        ),
        migrations.AlterField(
            model_name='cartpromociones',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[MODULOS.Carrito.validators.CantidadMayorCeroValidador]),
        ),
    ]
