# Generated by Django 3.2.6 on 2021-09-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='paga_con',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
