# Generated by Django 3.2.6 on 2021-09-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sector',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
