# Generated by Django 3.2.6 on 2021-09-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0002_empleado_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(default='NN', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
