# Generated by Django 3.2.6 on 2021-11-19 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0004_empleado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='usuario',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado'),
        ),
    ]
