# Generated by Django 3.2.6 on 2021-11-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_auto_20211124_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cliente.direccion'),
            preserve_default=False,
        ),
    ]
